// Package main enforces the repository coverage gate from the generated Go
// cover profile and Cobertura report.
// Authored by: OpenCode
package main

import (
	"bufio"
	"encoding/xml"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

var conditionCoveragePattern = regexp.MustCompile(`\((\d+)/(\d+)\)`)

// coberturaCoverage stores the top-level Cobertura metrics generated by
// gocoverageplus.
// Authored by: OpenCode
type coberturaCoverage struct {
	LinesCovered    int                `xml:"lines-covered,attr"`
	LinesValid      int                `xml:"lines-valid,attr"`
	BranchesCovered int                `xml:"branches-covered,attr"`
	BranchesValid   int                `xml:"branches-valid,attr"`
	Packages        []coberturaPackage `xml:"packages>package"`
}

// coberturaPackage stores one Cobertura package block.
// Authored by: OpenCode
type coberturaPackage struct {
	Classes []coberturaClass `xml:"classes>class"`
}

// coberturaClass stores one Cobertura class block, which maps to one receiver
// group within a Go source file.
// Authored by: OpenCode
type coberturaClass struct {
	Filename string          `xml:"filename,attr"`
	Lines    []coberturaLine `xml:"lines>line"`
}

// coberturaLine stores one Cobertura line entry.
// Authored by: OpenCode
type coberturaLine struct {
	Number            int    `xml:"number,attr"`
	Hits              int    `xml:"hits,attr"`
	Branch            string `xml:"branch,attr"`
	ConditionCoverage string `xml:"condition-coverage,attr"`
}

// branchCoverage stores one file-local branch coverage count.
// Authored by: OpenCode
type branchCoverage struct {
	Covered int
	Total   int
}

// statementBlock stores one unique Go cover profile block after duplicated test
// binary instrumentation is merged.
// Authored by: OpenCode
type statementBlock struct {
	Statements int
	Covered    bool
}

// fileCoverage stores one file's covered lines and branch counts.
// Authored by: OpenCode
type fileCoverage struct {
	LineHits map[int]int
	Branches map[int]branchCoverage
}

// main validates the generated coverage artifacts and exits non-zero when the
// repository's 100% gate is not met.
// Authored by: OpenCode
func main() {
	var profilePath = flag.String("profile", "dist/coverage/coverage.out", "Go cover profile path")
	var coberturaPath = flag.String("cobertura", "dist/coverage/coverage.xml", "Cobertura XML path")

	flag.Parse()

	statementCovered, statementTotal, err := readStatementCoverage(*profilePath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "coveragegate: %v\n", err)
		os.Exit(1)
	}

	report, err := readCoberturaCoverage(*coberturaPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "coveragegate: %v\n", err)
		os.Exit(1)
	}

	failures := validateCoverage(statementCovered, statementTotal, report)
	if len(failures) == 0 {
		return
	}

	for _, failure := range failures {
		fmt.Fprintf(os.Stderr, "coveragegate: %s\n", failure)
	}
	os.Exit(1)
}

// readStatementCoverage parses the Go cover profile and returns the covered and
// total statement counts.
// Authored by: OpenCode
func readStatementCoverage(path string) (int, int, error) {
	file, err := os.Open(path)
	if err != nil {
		return 0, 0, fmt.Errorf("open statement coverage profile: %w", err)
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	if !scanner.Scan() {
		if err := scanner.Err(); err != nil {
			return 0, 0, fmt.Errorf("read statement coverage profile: %w", err)
		}
		return 0, 0, fmt.Errorf("statement coverage profile is empty")
	}
	if header := strings.TrimSpace(scanner.Text()); !strings.HasPrefix(header, "mode:") {
		return 0, 0, fmt.Errorf("statement coverage profile header is invalid")
	}

	var blocks = map[string]statementBlock{}
	for scanner.Scan() {
		var rawLine = strings.TrimSpace(scanner.Text())
		if rawLine == "" {
			continue
		}

		fields := strings.Fields(rawLine)
		if len(fields) != 3 {
			return 0, 0, fmt.Errorf("statement coverage profile line is invalid: %q", rawLine)
		}

		numStatements, err := strconv.Atoi(fields[1])
		if err != nil {
			return 0, 0, fmt.Errorf("parse statement count from coverage profile: %w", err)
		}
		hitCount, err := strconv.Atoi(fields[2])
		if err != nil {
			return 0, 0, fmt.Errorf("parse hit count from coverage profile: %w", err)
		}

		var blockKey = fields[0]
		var block = blocks[blockKey]
		if block.Statements != 0 && block.Statements != numStatements {
			return 0, 0, fmt.Errorf("statement coverage profile block %q changed statement count", blockKey)
		}
		block.Statements = numStatements
		if hitCount > 0 {
			block.Covered = true
		}
		blocks[blockKey] = block
	}
	if err := scanner.Err(); err != nil {
		return 0, 0, fmt.Errorf("scan statement coverage profile: %w", err)
	}

	var covered int
	var total int
	for _, block := range blocks {
		total += block.Statements
		if block.Covered {
			covered += block.Statements
		}
	}
	if total == 0 {
		return 0, 0, fmt.Errorf("statement coverage profile did not contain executable statements")
	}

	return covered, total, nil
}

// readCoberturaCoverage parses the Cobertura XML emitted by gocoverageplus.
// Authored by: OpenCode
func readCoberturaCoverage(path string) (coberturaCoverage, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return coberturaCoverage{}, fmt.Errorf("read Cobertura report: %w", err)
	}

	var report coberturaCoverage
	if err := xml.Unmarshal(raw, &report); err != nil {
		return coberturaCoverage{}, fmt.Errorf("parse Cobertura report: %w", err)
	}

	return report, nil
}

// validateCoverage compares the generated statement, line, branch, and file
// metrics against the repository's 100% requirement.
// Authored by: OpenCode
func validateCoverage(statementCovered int, statementTotal int, report coberturaCoverage) []string {
	var failures []string

	if statementCovered != statementTotal {
		failures = append(failures, fmt.Sprintf("statement coverage is %s, expected 100%%", displayCoverageCount(statementCovered, statementTotal)))
	}
	if report.LinesCovered != report.LinesValid {
		failures = append(failures, fmt.Sprintf("line coverage is %s, expected 100%%", displayCoverageCount(report.LinesCovered, report.LinesValid)))
	}
	if report.BranchesValid > 0 && report.BranchesCovered != report.BranchesValid {
		failures = append(failures, fmt.Sprintf("branch coverage is %s, expected 100%%", displayCoverageCount(report.BranchesCovered, report.BranchesValid)))
	}

	var fileMetrics = collectFileCoverage(report)
	var filenames = make([]string, 0, len(fileMetrics))
	for filename := range fileMetrics {
		filenames = append(filenames, filename)
	}
	sort.Strings(filenames)

	for _, filename := range filenames {
		var metrics = fileMetrics[filename]
		var coveredLines int
		var totalLines int
		for _, hits := range metrics.LineHits {
			totalLines++
			if hits > 0 {
				coveredLines++
			}
		}

		var coveredBranches int
		var totalBranches int
		for _, branch := range metrics.Branches {
			coveredBranches += branch.Covered
			totalBranches += branch.Total
		}

		var displayName = displayPath(filename)
		if coveredLines != totalLines {
			failures = append(failures, fmt.Sprintf("file %s line coverage is %s, expected 100%%", displayName, displayCoverageCount(coveredLines, totalLines)))
		}
		if totalBranches > 0 && coveredBranches != totalBranches {
			failures = append(failures, fmt.Sprintf("file %s branch coverage is %s, expected 100%%", displayName, displayCoverageCount(coveredBranches, totalBranches)))
		}
	}

	return failures
}

// collectFileCoverage merges Cobertura class lines into file-level metrics.
// Authored by: OpenCode
func collectFileCoverage(report coberturaCoverage) map[string]*fileCoverage {
	var files = map[string]*fileCoverage{}

	for _, coveragePackage := range report.Packages {
		for _, class := range coveragePackage.Classes {
			if class.Filename == "" {
				continue
			}

			metrics := files[class.Filename]
			if metrics == nil {
				metrics = &fileCoverage{LineHits: map[int]int{}, Branches: map[int]branchCoverage{}}
				files[class.Filename] = metrics
			}

			for _, line := range class.Lines {
				if line.Hits > metrics.LineHits[line.Number] {
					metrics.LineHits[line.Number] = line.Hits
				}
				if line.Branch != "true" {
					continue
				}

				covered, total := parseConditionCoverage(line.ConditionCoverage, line.Hits)
				if existing, ok := metrics.Branches[line.Number]; !ok || total > existing.Total || covered > existing.Covered {
					metrics.Branches[line.Number] = branchCoverage{Covered: covered, Total: total}
				}
			}
		}
	}

	return files
}

// parseConditionCoverage converts a Cobertura branch summary into covered and
// total branch counts.
// Authored by: OpenCode
func parseConditionCoverage(raw string, hits int) (int, int) {
	var matches = conditionCoveragePattern.FindStringSubmatch(strings.TrimSpace(raw))
	if len(matches) == 3 {
		covered, coveredErr := strconv.Atoi(matches[1])
		total, totalErr := strconv.Atoi(matches[2])
		if coveredErr == nil && totalErr == nil {
			return covered, total
		}
	}

	if hits > 0 {
		return 1, 1
	}

	return 0, 1
}

// displayCoverageCount formats one coverage ratio for gate failures.
// Authored by: OpenCode
func displayCoverageCount(covered int, total int) string {
	return fmt.Sprintf("%d/%d", covered, total)
}

// displayPath converts an absolute report path into a repository-relative path
// when possible.
// Authored by: OpenCode
func displayPath(path string) string {
	relativePath, err := filepath.Rel(".", path)
	if err != nil || strings.HasPrefix(relativePath, "..") {
		return filepath.ToSlash(path)
	}

	return filepath.ToSlash(relativePath)
}
