// Package reportpdf provides shared font-backed PDF setup for black-box report tests.
// It imports the production renderer without importing package-local PDF tests,
// so it remains safe to reuse from contract, integration, and unit packages.
// Authored by: OpenCode
package reportpdf

import (
	reportmodel "github.com/benizzio/ghostfolio-cryptogains/internal/report/model"
	productionpdf "github.com/benizzio/ghostfolio-cryptogains/internal/report/pdf"
	"github.com/benizzio/ghostfolio-cryptogains/tests/testutil"
	"golang.org/x/image/font/gofont/gobold"
	"golang.org/x/image/font/gofont/goregular"
)

// NewRenderer creates the standard application-font PDF renderer used by
// black-box report tests. Callers that need to assert renderer failures can use
// the returned renderer directly, preserving the original payload and error.
//
// Example usage:
//
//	renderer, err := reportpdf.NewRenderer()
//	if err != nil {
//		t.Fatal(err)
//	}
//	payload, err := renderer.Render(report)
//
// Authored by: OpenCode
func NewRenderer() (productionpdf.Renderer, error) {
	return productionpdf.NewRenderer(productionpdf.RenderOptions{
		Fonts: productionpdf.FontData{Regular: goregular.TTF, Bold: gobold.TTF},
	})
}

// Render creates the standard renderer and returns a successful report PDF
// payload. Use NewRenderer instead when the test must distinguish renderer
// construction from report-rendering failure or inspect a nil failure payload.
//
// Example usage:
//
//	payload, err := reportpdf.Render(report)
//	if err != nil {
//		t.Fatal(err)
//	}
//	_ = payload
//
// Authored by: OpenCode
func Render(report reportmodel.CapitalGainsReport) ([]byte, error) {
	var renderer, err = NewRenderer()
	if err != nil {
		return nil, err
	}

	return renderer.Render(report)
}

// RenderAndInspect renders a successful report with the standard renderer and
// parses its generated bytes through the shared PDF inspection model. It is
// intended for contract assertions that only need recovered PDF evidence.
//
// Example usage:
//
//	inspection, err := reportpdf.RenderAndInspect(report)
//	if err != nil {
//		t.Fatal(err)
//	}
//	if !inspection.ContainsSearchableText("Annex 1 - Audit") {
//		t.Fatal("missing Annex heading")
//	}
//
// Authored by: OpenCode
func RenderAndInspect(report reportmodel.CapitalGainsReport) (testutil.GeneratedPDF, error) {
	var payload, err = Render(report)
	if err != nil {
		return testutil.GeneratedPDF{}, err
	}

	return testutil.InspectGeneratedPDF(payload)
}
