name: Test

permissions:
  contents: read

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test-suite.yml
    with:
      make-target: test
      timeout-minutes: 10

  coverage:
    uses: ./.github/workflows/test-suite.yml
    with:
      make-target: coverage
      timeout-minutes: 15

  test-performance:
    uses: ./.github/workflows/test-suite.yml
    with:
      make-target: test-performance
      timeout-minutes: 15
